spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/whale_photo"
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    baseline-on-migrate: true

file:
  upload-directory: "/uploads"